### ISSUE TITLE
Create Requirements Page

### ISSUE THREAD

**Issue by bestegoger** [bounswe/bounswe2020group9#10]
Add functional and non-functional requirements. 
Use Google Docs document.
**Deadline: 24.02.2020 23:59**

**Comment by bestegoger** [comment]
User requirements are done. Please check it.

**Comment by uskudarli** [comment]
Looking at this thread, I can't see where the "it" is? Where are the requirements?

Also, recall that all group documentation is to be in Wiki format. It is okay to work with google docs while developing, but they should be transferred to Wiki

**Comment by bestegoger** [comment]
I added a link to the "User Requirements" section of the Requirements wiki page.
Thanks for the comment. :blush:

**Comment by hasandemirkiran** [comment]
Extend the Non-functional subcategory. Review the whole doc.

**Comment by ocebenzer** [comment]
Added Shortcuts and done with the Non-Functional Requirements
2.1.1 **modern web browsers** needs detailed explanation
Additional review may be needed

**Comment by ibrahimorhan** [comment]
1.1.14.2 has been modified. 'delivered' and 'cancelled' status are added
1.2.4.4. has been added Admins can send notification to vendors about a problem
2.3.4 has been added. Admin can keep track of transaction

**Comment by ocebenzer** [comment]
Can Customer and Vendor save their card info?
