### ISSUE TITLE
Discussion to determine the platform to be used on the mobile side

### ISSUE THREAD

**Issue by muhsinetki** [bounswe/bounswe2020group9#101]
We have two options, these are iOS and Android

1. iOS

- Xcode 

- Swift

2. Android

- Android Studio

- React

**Comment by muhsinetki** [comment]
Following the discussions made throughout the group, the following conclusion has been reached. It has been decided that the members of the group who have experience on mobile are more experienced in the ios part compared to the android and using ios instead of android would be more correct.

**Comment by alcanunsal** [comment]
I think iOS would be more feasible since me and Muhsin has experience with it. If Beste and Şadi are okay with learning Swift and the teaching staff approve, we should proceed with iOS.

**Comment by alcanunsal** [comment]
I'm closing this issue as we decided on iOS development with Xcode and our teaching staff has approved this decision.
