### ISSUE TITLE
Backend Implementation

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#103]
Start backend implementation according to the project plan.

**Comment by ocebenzer** [comment]
As you know, our final implementation will be from an online excel sheet
You should have the link to the sheet by now

**Comment by ocebenzer** [comment]
The initial repository is available with [a small guide on how to get it to run](https://github.com/bounswe/bounswe2020group9/blob/Backend/Projects/Backend/readme.md)
Also the very initial tables for User-Product relation is on!
Althought there might be a lot stuff to fill, it looks good for now

Do not forget to create a new branch and [merge from there to Backend](https://github.com/bounswe/bounswe2020group9/pull/113), not [into master](https://github.com/bounswe/bounswe2020group9/pull/112)

**Comment by mehmetkemaloglu** [comment]
Good job Ömer. Initial repository looks nice. Lets schedule a meeting today to discuss last meetings topics and decide how to proceed on project. I'm available today.

**Comment by sadiuysal** [comment]
Since initial planning and coding phase completed, we can close this issue.
