### ISSUE TITLE
IOS Implementation

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#105]
Start to implement IOS application according to the project plan.

**Comment by alcanunsal** [comment]
For now, we are waiting for the teaching staff's decision about proceeding with iOS. after it is certain that we can work with native iOS instead of android, we will start the implementation.

**Comment by sadiuysal** [comment]
Meanwhile we can set up a meeting as mobile dev team to discuss further actions.

**Comment by muhsinetki** [comment]
Today we can have a meeting after the lab, if it's ok for everyone

**Comment by alcanunsal** [comment]
Fyi I shared the tutorial links, demo codes and lecture slides for the Stanford tutorials as we discussed via our Slack channel.

**Comment by alcanunsal** [comment]
We've started working on the home page.

**Comment by sadiuysal** [comment]
We pushed first commit to the repository.

**Comment by muhsinetki** [comment]
The initial setup has been done and the table view showing the products on the main screen has been added. Also the logo and search bar have been added.

**Comment by alcanunsal** [comment]
I have added the tab bar functionality to the main screen.

**Comment by sadiuysal** [comment]
Since initial planning and coding phase completed, we can close this issue.
