### ISSUE TITLE
Update Wiki Page

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#107]
Update Wiki page with some changes, for example add new members, diagrams, meeting notes.

**Comment by alcanunsal** [comment]
We as mobile team added 2 meeting notes.

**Comment by alcanunsal** [comment]
Just a reminder: if you are senior this year, some of you may have forgotten to update your personal wiki page. Many of our personal wiki pages says that we are juniors, not seniors.

**Comment by hasandemirkiran** [comment]
Thanks for reminding @alcanunsal , when everyone updated her personal wiki pages. We can close the issue.

**Comment by ocebenzer** [comment]
Thank you, thats a good point

**Comment by firatbulut19** [comment]
I updated it, thanks for the heads up.

**Comment by sadiuysal** [comment]
@gkhntkl  Could you redesign your personal wiki page in a more descriptive way similar to other group members ? Other than that, I checked the personal wiki pages, I think we can close this issue after @gkhntkl  completed his page.

**Comment by gkhntkl** [comment]
All done.
