### ISSUE TITLE
Decide next meeting

### ISSUE THREAD

**Issue by sadiuysal** [bounswe/bounswe2020group9#108]
I suggest setting up a meeting at 05.11.2020 22:30, Thursday.  Please respond with your alternative available slots if it is not suitable for you.

**Comment by neutralsecond** [comment]
It's fine for me.

**Comment by ibrahimorhan** [comment]
It is okay for me

**Comment by bestegoger** [comment]
Thursday 22:30 is fine with me 👍

**Comment by muhsinetki** [comment]
It is okey for me

**Comment by sadiuysal** [comment]
Worth to mention class diagram review for the meeting. Keep that in mind

**Comment by m-canunal** [comment]
it is okey for me also .

**Comment by firatbulut19** [comment]
It's fine by me too

**Comment by hasandemirkiran** [comment]
Fits for me

**Comment by ocebenzer** [comment]
ok for me too

**Comment by alcanunsal** [comment]
date and time is okay for me

**Comment by gkhntkl** [comment]
it is fine for me
