### ISSUE TITLE
B1- Backend Meeting 

### ISSUE THREAD

**Issue by ibrahimorhan** [bounswe/bounswe2020group9#110]
We should set a meeting for updating class diagram and making a small demo for django. Is it okey to set it on 3.11.2020,20:00

**Comment by mehmetkemaloglu** [comment]
Yes, we can set it on that time.

**Comment by ocebenzer** [comment]
ok, at 8pm we should be able to group up

**Comment by ocebenzer** [comment]
[Meeting Report](https://github.com/bounswe/bounswe2020group9/wiki/Backend-Meeting-1)
we can continue talking about Backend issues from [This Issue Page](https://github.com/bounswe/bounswe2020group9/issues/103)
