### ISSUE TITLE
Mobile Team Meetings

### ISSUE THREAD

**Issue by bestegoger** [bounswe/bounswe2020group9#111]
I suggest to set a meeting to initiate the implementation. It would be great to start and decide on some designs together.
Let's vote for Saturday 07.11.2020, 20:00.

**Comment by alcanunsal** [comment]
will we be able to do a meeting today?

**Comment by alcanunsal** [comment]
we could do tomorrow at 8 pm if that's okay for everyone?

**Comment by sadiuysal** [comment]
Sure

**Comment by muhsinetki** [comment]
It is fine for me

**Comment by bestegoger** [comment]
It is okay for me 👍

**Comment by alcanunsal** [comment]
Second meeting took place today at 8 pm and I added the meeting notes to wiki.

**Comment by sadiuysal** [comment]
Since we had done this meeting, we can close this issue. You can access meeting notes via our [wiki](https://github.com/bounswe/bounswe2020group9/wiki).
