### ISSUE TITLE
Determine Project Logo and Project Name

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#13]
Deadline is 1st of March.

**Comment by neutralsecond** [comment]
Does the name have to be in English?

**Comment by bestegoger** [comment]
As a starter, I suggest GrandBazaar as our project name. 🤓

**Comment by ibrahimorhan** [comment]
I think it is better as only Bazaar

**Comment by neutralsecond** [comment]
What about Lady's Bazaar :)

**Comment by hasandemirkiran** [comment]
Suggests:
e(asy)-Buy
Online-Bazaar
Bazaar-Place

**Comment by neutralsecond** [comment]
Here is the voting link
https://cmpe352g9.slack.com/archives/CUB9644EN/p1583072237003200

**Comment by sadiuysal** [comment]
It seems "Bazaar" won the project name voting.

**Comment by alcanunsal** [comment]
By the results of voting in slack, I added the logo here:
https://github.com/bounswe/bounswe2020group9/blob/master/Media/bazaar-4.png
