### ISSUE TITLE
Decide branch name convention and design 

### ISSUE THREAD

**Issue by sadiuysal** [bounswe/bounswe2020group9#131]
We decided to update our branch design and name convention. Please update your branch names accordingly.
Example design convention:
* master
* * ios_master
* * * ios_sadi_homepage
* * frontend_master
* * * frontend_hasan_homepage
* * backend_master 
* * * backend_omer_homepage

**Comment by ocebenzer** [comment]
It's good to have a standart, this looks nice
We might need to change the names of old branches

**Comment by hasandemirkiran** [comment]
I think this is a very good improvement. Need to be done.

**Comment by ocebenzer** [comment]
It looks like the proper way to rename old branches is to create a new branch based of the old branch, and then delete the old branch.

**Comment by alcanunsal** [comment]
thanks, @ocebenzer I was looking for a way to do that 👍

**Comment by sadiuysal** [comment]
I changed branch structure for the mobile part according to convention. You can see new structure via this [link](https://github.com/bounswe/bounswe2020group9/network)

**Comment by sadiuysal** [comment]
Redesigned branches according to convention. We can close the issue.
