### ISSUE TITLE
sign in/sign up screens for iOS

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#137]
we should plan how we are going to implement the sign in and sign up screens. maybe we could set up a meeting for it?

**Comment by muhsinetki** [comment]
Yes it's a good idea to arrange a meeting for this.

**Comment by muhsinetki** [comment]
I implemented the sign in and sign up screens.

**Comment by muhsinetki** [comment]
Since the implementation of the login and sign up screens is complete, we can close this issue.
