### ISSUE TITLE
Construct Scenario: Vendor Selling an Item

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#14]
We need to construct a scenario where the vendor receives an order and the stock of that item is insufficient. The vendor needs to contact with both the admin and the buyer in order to properly go through with the sales process.

**Comment by ibrahimorhan** [comment]
Scenario has changed. Now we think of a vendor having problem with cargo

**Comment by hasandemirkiran** [comment]
From the requirements; vendor used the website (not with the android application as a platform) and sign up with the google account (not with the e-mail and password)

**Comment by ibrahimorhan** [comment]
Acceptance of requirements should be written

**Comment by hasandemirkiran** [comment]
A useful website to generate mock-ups:
https://www.mockflow.com

**Comment by alcanunsal** [comment]
Mockups as well as the scenario is completed and added under "User Scenario 1" in wiki.
