### ISSUE TITLE
API call standardization

### ISSUE THREAD

**Issue by ocebenzer** [bounswe/bounswe2020group9#140]
We should assume the GET method for product as such:
```
call to: "/api/product/get"
body: "{'id':'17'}"
``` 
which returns:
```
body: 
"{
    'status':'200',
    'product':{
        'name': 'Fıstık, 200gr',
        'price': '12.99',
        'brand': 'tadım',
        'categories': ['Çerezler', 'Yiyecek', 'Ürünler'],
        'labels': ['Fıstık', 'Kuruyemiş', 'Protein', 'Yiyecek'],
        'stock': '25000',
        'sell_counter': '17000'
        'rating': '4.95',
        'vendor': {
            <vendor>
        },
        'comments': [
            <comment>
        ],
    }
}"
```
Note that vendor and comment are not filled for now

Status: 200 is OK, the request is succesful. Sell counter is the amount that product has been sold.
Other than that I think names are self explanotory.

Besides 200, there are error status codes, for example 404 not found:
```
body: "{'status':'404'}"
```
or 400 bad request
```
body: "{'status':'400'}"
```
Since there is no product to fetch, one should check the error code before product. For now, we plan to implement 400 and 404 only, any error besides not found will be displayed on 400

Are there any edge cases left?

**Comment by sadiuysal** [comment]
Looks nice. We can enhance this baseline if needed.

**Comment by firatbulut19** [comment]
Yes, this looks good.
For the upcoming milestone, we will need a GET request according to category. Something like this:
Call to: “api/product/get_category”
Body {‘category’: ‘technology’} or {‘category_id’: 6}
How can we implement this? What would the responding JSON contain? 
You could maybe send some premade list of products to make it less time consuming for now. You can improve on it after the milestone.

**Comment by ocebenzer** [comment]
I just found out that status code is already in the response, it does not need to be in the JSON. What if we remove it?
It would be[ like this](https://prnt.sc/vlkbwo) if it is removed. 
Additionaly, we can change small stings if needed.

**Comment by ocebenzer** [comment]
Our plan for the presentation needs dummy instances. I used my creativity as much as possible(!) and created some background for the presentation.

Current .sqlite3 file is also available on slack, feel free to add or change instances

**Comment by ocebenzer** [comment]
There is going to be a detailed postman collection where all API requests are documented. You can find it in our Slack channel.  As the backend team, we plan to update it whenever we make an improvement.

Feel free to ask us to add/update urls for your need, or if there is a problem about documentation.
