### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#144]
Here is the what we use for a color palette for the web site. 

https://colorhunt.co/palette/213437

Please review

**Comment by alcanunsal** [comment]
I think the colors you chose are beautiful, however since the logo is mostly orange, I am not sure they would suit with the logo. If everyone is okay with it it's fine by me though

**Comment by muhsinetki** [comment]
I agree with alcan, while developing on the mobile side, I mostly used shades of orange
