### ISSUE TITLE
Construct Scenario: Customer Buying an Item

### ISSUE THREAD

**Issue by bestegoger** [bounswe/bounswe2020group9#15]
Construct a scenario where a customer searches and after several steps purchases an item. 
Create mock-ups.
The discussion will be held on [Slack #scenario_2 channel](https://cmpe352g9.slack.com/archives/CU6V9SH34). Please join as soon as possible! :blush:
**Deadline: 02.03.2020 23:59**

**Comment by hasandemirkiran** [comment]
A useful website to generate mock-ups:
https://www.mockflow.com

**Comment by bestegoger** [comment]
I added Scenario 2. You can find it [here](https://github.com/bounswe/bounswe2020group9/wiki/Scenario2).
