### ISSUE TITLE
Scenario 3: Customer Cancelling an Item

### ISSUE THREAD

**Issue by neutralsecond** [bounswe/bounswe2020group9#16]
We need to construct a scenario and prepare mock-ups for a customer who wants to return an item that s/he bought before. [Here](https://app.slack.com/client/TU3ERSM1U/CUKPLT51B) is the slack channel we will use. Deadline is **02.03.2020 / 23:59**

**Comment by hasandemirkiran** [comment]
A useful website to generate mock-ups:
https://www.mockflow.com

**Comment by muhsinetki** [comment]
Scenario, goals  and person parts are completed
In addition, the person's photo has been added.

**Comment by ocebenzer** [comment]
All done but Acceptance Criteria.
mockups are ready and ready to deploy whenever we can

**Comment by ocebenzer** [comment]
Done but it might need interview

**Comment by ocebenzer** [comment]
Review of the Scenario and its mockup is ongoing

**Comment by ocebenzer** [comment]
I think it looks done?
