### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#174]
Please review the categories and subcategories. 

'Electronics', 'House', 'Kitchen', 'Sport', 'Food', 'Laundry', 'Garden', 'Books', 'Fitness', 'Cosmetics', 'Fashion', 'New', 'Sale'

These are the categories we have determined as a frontend team.

**Comment by alcanunsal** [comment]
We as mobile team think that the main categories should be: Electronics, Home, Living (for Sports and art supplies etc), Books, Selfcare (cosmetics, beauty, hygiene etc), Fashion. I think we can further discuss the subcategories.

**Comment by sadiuysal** [comment]
I agree with Alcan.

**Comment by bestegoger** [comment]
Totally agree about building a consensus about the categories. And Alcan's offerings look okay to me for the main categories.

**Comment by firatbulut19** [comment]
Fewer categories will make things cleaner I think. I agree with Alcan. 
'Books' feels like more of a subcategory (of Living) than a category itself.
We can expand them with subcategories later.
For the sake of having some sample subcategories, I can suggest:
Electronics[Smartphone, Tablet, Computer, Home appliances, Other]
Fashion[Pants, Shorts, T-shirt, Dress, Suit, Accessories, ..]
Home[Furniture, Table&chairs, Wardrobe, Bed, ..]

**Comment by alcanunsal** [comment]
I think @firatbulut19 is right about books being a subcategory of living. Other than that, I could continue upon the suggested subcategories:

electronics -> Smartphone, Tablet, Computer, Photography, Home Appliances, TV, Gaming, Other
fashion -> Top, Bottom, Outerwear, Shoes, Bags, Accesories, Activewear 
home -> Home Textile, Kitchen, Bedroom, Bathroom, Furniture, Lighting, Other
living -> Books, Art Supplies, Musical Devices, Sports, Other
selfcare -> Perfumes, Makeup, Skincare, Hair, Body Care, Other

Let me know if you think we should go with this or add/remove any subcategories.

**Comment by ocebenzer** [comment]
It looks really good! But I want to ask a few questions: 

- Wouldn't it be better to call _fashion_ something different? Maybe something along _clothing_ or _wearing_. I'm not sure since this causes problems for some subcategories like _shoes_ or  _accesories_. They would not be inside the category anymore.
 - What would _textile_ represent, or what is a product within _textile_?

**Comment by alcanunsal** [comment]
@ocebenzer i think clothing sounds good! i didn't think about it the first time but it is much better than fashion in my opinion too. 

by "textile" i think you mean "home textile", which is stuff like nevresim, curtains, rugs, havlu, etc. it is present in most of the home decor categories in e-commerce platforms.

**Comment by alcanunsal** [comment]
Since we decided on the categories and their respective categories, I am closing this issue.
