### ISSUE TITLE
api calls for cart - some problems

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#217]
when I send a GET request to  http://13.59.236.175:8000/api/user/6/cart/ I get the following response:
`response: success({
  detail = “Not found.“;
})`

when I send a POST request to the same url, I get this response:
`success({
  detail = “Method \“POST\” not allowed.“;
})`

In the api documentation, it says that I can make PUT and GET requests to this url and I would like your help on this issue. Is this because the user does not have a cart (but i don't think so because the user has a list named "cart" which I believe is the cart of the user) or is there something wrong that I'm doing or the API has problems?

**Comment by ocebenzer** [comment]
There are 2 problems:
1. The request was supposed to be `/api/user/cart/`, which we wrote wrong.
2. Even after that, the deployed server has small issues and it needs to be updated, it should be working as intended in a few hours.

**Comment by ocebenzer** [comment]
The problem appears to be that you token is a vendor, not a customer. Can you retry with the token I sent you?

**Comment by alcanunsal** [comment]
I tried the token you sent me, however when I search for the error online, it seems like the response from the request is not in JSON format, therefore the library we use in Swift to make api requests return an error. Are you sure that the response for that request is in JSON format?

**Comment by ocebenzer** [comment]
for now, the response is `[]`,which means it's empty
can you retry again, i added a dummy element

**Comment by alcanunsal** [comment]
Thank you, I think this solved the problem although I am not sure why :D Anyways, thank you very much for your help :)
