### ISSUE TITLE
Requirements Review

### ISSUE THREAD

**Issue by sadiuysal** [bounswe/bounswe2020group9#22]
Every group member should review the [requirements](https://github.com/bounswe/bounswe2020group9/wiki/Requirements) since there will be revisions according to customer's answers.

**Comment by ocebenzer** [comment]
I updated the requirements page based on the review. However, there is a lot to consider and we need to fufill any other details I might've not seen.
- There are TODOs in the glossary, please sort them alphabetically after filling.
- Bazaar contract should be a legal file which users should read and approve when signing up.

Here is the review of the assistant: https://piazza.com/class/k5z7hzm7ncm1m3?cid=70

**Comment by sadiuysal** [comment]
Final version of the requirements are uploaded. You can access it via this [link](https://github.com/bounswe/bounswe2020group9/wiki/Requirements).
