### ISSUE TITLE
Sign In Sign Up With Google

### ISSUE THREAD

**Issue by ibrahimorhan** [bounswe/bounswe2020group9#228]
Sign in and Sign up with Google functionality will be added to server until 26.12.2020, 23:59

**Comment by ocebenzer** [comment]
I think sign via google is available @ibrahimorhan

**Comment by ibrahimorhan** [comment]
Yes, I forgot to write to issue. All descriprions and documentations can be found in API Documentation in wiki page and Discussions

**Comment by ibrahimorhan** [comment]
Thank you for reminding
