### ISSUE TITLE
iOS - Review&Comments View

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#235]
If possible, review and comments view controller should be implemented as discussed in iOS Meeting #6. The segue connection from ProductDetailViewController should also be implemented.

Deadline: 28.12.2020 23.59

**Comment by bestegoger** [comment]
I have started implementing this feature working on the branch `ios_beste_reviews-page`.
- When "View Reviews" button is clicked on Product Detail Page user will see the reviews page and all comments available for that product. 
- For now only the non-anonymous comments are handled. 


**Future Work:**
- Design needs to be improved.
- User's comment for the product needs to be displayed/ editable.
- Anonymous comments need to be handled.

**Comment by bestegoger** [comment]
Since the reviews functionality is done, I am closing this issue.
