### ISSUE TITLE
iOS - Design Conventions

### ISSUE THREAD

**Issue by bestegoger** [bounswe/bounswe2020group9#254]
In my opinion, there is a confusion in our project about the top bars. 

Some of the view controllers have navigation bar but some don't.  For me having the stack view with the logo as the top bar looks good but if we need the back button in many cases we can decide on having the top bar, otherwise we can use a custom back button when needed. 

So, it would be great if we can discuss and move further with the best design that fits in.

**Comment by alcanunsal** [comment]
I agree with you, maybe we could talk about it in our meeting tonight and do the necessary changes.

**Comment by bestegoger** [comment]
Since we discussed in the meeting and did the necessary arrangements, I am closing this issue.
