### ISSUE TITLE
Documentation of Customer Meeting

### ISSUE THREAD

**Issue by muhsinetki** [bounswe/bounswe2020group9#27]
### Deadline 09.03.2020 23:59

Go over all details of customer's answers and responsibilities related to documentation.

- [x] Muhsin Etki

- [x] Hasan Demirkiran

**Comment by muhsinetki** [comment]
I added the notes I got

**Comment by hasandemirkiran** [comment]
All the notes are completed and reviewed  with the latest version. Anyone attend the meeting can check and free to comment
