### ISSUE TITLE
iOS - Vendor Side Development

### ISSUE THREAD

**Issue by muhsinetki** [bounswe/bounswe2020group9#270]
I made the first setup, let's clarify some issues until the end of the lab tomorrow.

- [ ] Which color will we use
- [ ] Determining the improvements to be made in the API with the backend team
- [ ] Clarifying and dividing the works to be done

**Deadline: 12.01.2021 17.00**

**Comment by sadiuysal** [comment]
* I think we may use similar colors from the frontend side for the vendor part. 
* We discussed and listed improvements to be made for the backend. We also divided works to be done.  Details can be found [here](https://docs.google.com/spreadsheets/d/1TU0nmEY7OZrgaHi3jZResZVsoKU_zL7ppRukiXhTDC8/edit?usp=sharing).

**Comment by muhsinetki** [comment]
Hex value of the color we will use on the vendor side: 41aea9
from : https://colorhunt.co/palette/213437
