### ISSUE TITLE
Vendor Sign Up Bug

### ISSUE THREAD

**Issue by muhsinetki** [bounswe/bounswe2020group9#282]
While trying to sign up for vendor, the response from api is as follows

`{
    "email": [
        "Couldn't send email"
    ]
}`

Could you please provide necessary information when the error is resolved ?

**Deadline: 20:01.2021 23:59**

**Comment by ibrahimorhan** [comment]
Bug is not caused by the code it happened because of Google. I have created new account and changed the mail settings. It will be corrected in the next deploy.
