### ISSUE TITLE
Backend - My Addresses

### ISSUE THREAD

**Issue by muhsinetki** [bounswe/bounswe2020group9#295]
Can you provide the necessary information after improvements have been made on the backend so that users can add address information and then delete or update them whenever they want?

**Deadline 20.01.2021 23:59**

**Comment by muhsinetki** [comment]
Any progress?

**Comment by mehmetkemaloglu** [comment]
Currently, 5 different location API call is available in the API documentation. If you want to use another API for locations, feel free to ask to the backend team to implement it.

**Comment by muhsinetki** [comment]
Thank you for your efforts, everything is working fine
