### ISSUE TITLE
Message API - message order is reversed

### ISSUE THREAD

**Issue by ocebenzer** [bounswe/bounswe2020group9#308]
right now `/api/messages/all/` orders the messages in least-recent order
however/api/messages/<id>/ orders in the most-recent order
i think this was not intended

**Comment by mehmetkemaloglu** [comment]
You are right, this was not intended of course. I forgot to check the order before the commit. I can fix this easily. Which order do you prefer?

**Comment by ocebenzer** [comment]
I think least-recent would be better

**Comment by ocebenzer** [comment]
bug fixed, closing the issue
