### ISSUE TITLE
Creating Class Diagram

### ISSUE THREAD

**Issue by ocebenzer** [bounswe/bounswe2020group9#31]
Creating the Class Diagram page for the project

**Comment by ocebenzer** [comment]
Is the project delayed due to coronavirus?

**Comment by ocebenzer** [comment]
The skeleton of the Class diagram is complete. Note that every detail of the requirements page and scenarios should be specified.
- Pointing arrows should be the parent classes.
- Square arrows are related, they are used as static classes or as variable objects.

TODO:
- The parameters and functions are still messy, we need to rewrite them. Default getters and setters looks odd, I think we should remove some of those if not all. 
- ANYTHING WE MISSED, because we must've.
- Google user looks weird, we gotta find a solution for it.

The scheme: https://app.moqups.com/3AZFs9xIMs/view. Any comment would be appreciated.

**Comment by ibrahimorhan** [comment]
I think get and set functions are necesaary and we didn't write most of them. We should complete that
