### ISSUE TITLE
Update Sequence Diagram

### ISSUE THREAD

**Issue by sadiuysal** [bounswe/bounswe2020group9#36]
Please update the necessary parts of sequence diagrams.

**Comment by sadiuysal** [comment]
***
Updated those sequence diagrams.
Login via username:

![login via username](https://user-images.githubusercontent.com/23438455/80304103-bba55f00-87bc-11ea-9a61-c895397d1c00.png)
***

Add to List:

![add to list](https://user-images.githubusercontent.com/23438455/80303856-82202400-87bb-11ea-840c-b4f32668deb5.png)

***

Filter:

![Filter](https://user-images.githubusercontent.com/23438455/80303852-7fbdca00-87bb-11ea-8973-906dd1246174.png)

***

Ban User:

<img width="825" alt="ban user" src="https://user-images.githubusercontent.com/23438455/80303854-81878d80-87bb-11ea-8b05-0c34eb8f5169.png">

***

**Comment by alcanunsal** [comment]
Updated "Search" sequence diagram.
