### ISSUE TITLE
News API implementation

### ISSUE THREAD

**Issue by ibrahimorhan** [bounswe/bounswe2020group9#48]
Implementation of News API until 27.05.2020, 23.00

**Comment by ocebenzer** [comment]
New branch: API_Development_Favorites
Added 3 routes: "/api", "/api/add", "/api/remove"
These routes can view, add or remove a custom json file
They can handle in order: GET, POST, DELETE requests
Is there a way to combine them into one route: "/api" without causing a problem? Maybe something like if (request == "GET") elif (request =="POST") etc..

**Comment by ibrahimorhan** [comment]
New branch "newsAPI"  is created

**Comment by firatbulut19** [comment]
Added 2 routes: "/news", "/newsNasa".
Both handle GET requests.
"/news" returns a json file containing the most popular news articles about a certain topic. Topic and origin country are specified by the user.
"/newsNasa" returns a json file containing the most popular news articles that contain the keyword [owner of today's Astronomy picture from NASA API]

**Comment by ibrahimorhan** [comment]
I have carried class that Ömer implemented to "newsAPI" branch. Also added getMaxDate function and carried "newsNasa" on the new commit. However app.py and bazaar.py should be updated

**Comment by ibrahimorhan** [comment]
"Dandelion API" added for the entity extraction of apod explanation.  Also "sortByConfidence method added to utils.py

**Comment by ibrahimorhan** [comment]
"/api/news/nasa" route added. "get_news" call separated and "get_nasa_news" added. Case of no article should be handled.

**Comment by ibrahimorhan** [comment]
"newsAPI" branch is merged with "API_Development" branch [pull request](https://github.com/bounswe/bounswe2020group9/pull/65)

**Comment by firatbulut19** [comment]
New branch news_unit_test is opened. All test cases for News API will be written here.

**Comment by ibrahimorhan** [comment]
test_early_date_nasa
test_early_date_news
test_input_format_nasa
test_input_format_news
test_output_format_nasa
test_output_format_news
Tests are added. also checkInputFormat added to utils.py to " news_unit_test" branch

**Comment by firatbulut19** [comment]
Added test cases:
test_recent_date_news
test_recent_date_nasa
test_forward_date_news
test_forward_date_nasa
Also made some minor adjustments on utils.py and api_calls.py.

**Comment by ibrahimorhan** [comment]
I have solved the problem which api call returns null urlToImage.

**Comment by sadiuysal** [comment]
Implementation of News API is done.
