### ISSUE TITLE
Research GitHub repos

### ISSUE THREAD

**Issue by firatbulut19** [bounswe/bounswe2020group9#5]
Research GitHub and try to find interesting, useful repos. You can share your findings [here](https://github.com/bounswe/bounswe2020group9/wiki/Repository-Research).
Every group member should participate.

**Comment by ocebenzer** [comment]
Pages that needs update:
"FreqTrade", "awesome-python", "Bootstrap", "Node.js", "Awesome Cheatsheets", "Free programming books" and "🤓 Build your own (insert technology here)"

Vanilla JS can be explained a bit better
Anything else?

**Comment by hasandemirkiran** [comment]
Update: Review the project description and write the project description with our own sentences.

**Comment by sadiuysal** [comment]
I examined the repos and changed necessary description parts.
