### ISSUE TITLE
Front-end Implementation

### ISSUE THREAD

**Issue by ibrahimorhan** [bounswe/bounswe2020group9#57]
Front end should be implemented until 27.05.2020, 23.00

**Comment by ibrahimorhan** [comment]
I have created the "Frontend-News" branch to implement the front end for the news part. It will be merged with "Frontend" branch

**Comment by alcanunsal** [comment]
Implemented basis for an alternative home page design in homepage.html in Frontend branch. We can continue with this style or go back to the old one if we want.

**Comment by hasandemirkiran** [comment]
Some changes are made for the footer, part to fill API contents are clearly identified in index.html. Github icon, bazaar logo etc.

**Comment by ocebenzer** [comment]
Backend is almost complete! We can remove branches if the job is done, this will reduce the complexity and it will look pretty.

Now we can solely focus on Frontend, to do so:
Use FrontEnd_Development as parent and open new branches as needed. For example, FrontEnd_Development_Currency is a branch based on FrontEnd_Development.

**Comment by alcanunsal** [comment]
Frontend for Weather API and APOD API are done.

**Comment by sadiuysal** [comment]
Currency API frontend part is done.

**Comment by alcanunsal** [comment]
Our frontend implementation is done, therefore I am closing this issue.

**Comment by sadiuysal** [comment]
Frontend implementation is completely done.
