### ISSUE TITLE
Find API's for Covid tracking

### ISSUE THREAD

**Issue by mehmetkemaloglu** [bounswe/bounswe2020group9#59]

**Comment by mehmetkemaloglu** [comment]
The following API looks good. We have lots of alternatives in this API. According to our group project, we have to request the data by indicating the date.

https://api.covid19api.com/

**Comment by muhsinetki** [comment]
We can use the following API

https://api.covid19api.com/world

https://api.covid19api.com/country/south-africa?from=2020-03-01T00:00:00Z&to=2020-04-01T00:00:00Z

**Comment by alcanunsal** [comment]
Since we found an API for COVID tracking, maybe we could close this issue.

**Comment by muhsinetki** [comment]
We're done here.
