### ISSUE TITLE
Arrange Meeting #2

### ISSUE THREAD

**Issue by firatbulut19** [bounswe/bounswe2020group9#6]
Arrange time and place for the 2nd meeting.

**Comment by mericturan** [comment]
Dear all,

This issue requires the attention of the whole team, not a particular team member. Therefore, why is Muhsin the only assignee?

Also, again I can neither see a discussion nor the result of the issue. It is too late for the discussion, but at least state the resulting meeting time and venue.

Note that unlike this particular issue, issues should be trackable.

**Comment by neutralsecond** [comment]
2nd meeting took place at 13:00 in the department building, A6.

**Comment by muhsinetki** [comment]
> 2nd meeting took place at 13:00 in the department building, A6.

On Thursday 20.02.2020
