### ISSUE TITLE
Weather API Development 

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#61]
Develop Weather Forecast API.

**Comment by hasandemirkiran** [comment]
Some Weather API suggestions:

https://openweathermap.org/api
http://forecast.io
http://www.wunderground.com/weather/api/

**Comment by alcanunsal** [comment]
Most of the Historical Weather API development is done, now it just needs some improvements after merging with API_Development branch.

**Comment by hasandemirkiran** [comment]
Improvements and test cases are done, anything to review please up again.
