### ISSUE TITLE
Set up Slack

### ISSUE THREAD

**Issue by firatbulut19** [bounswe/bounswe2020group9#7]
Set up Slack workspace to enhance communication among the group.

**Comment by ocebenzer** [comment]
Slack seems like it benefits nothing that whatsapp and GitHub doesn't. We plan to not use it for now

**Comment by ocebenzer** [comment]
Even if we plan not to use it, for future references here is the link to our Slack workspace:
cmpe352g9.slack.com

**Comment by ocebenzer** [comment]
We've decided to use Slack once again
