### ISSUE TITLE
Weather API Frontend Implementation

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#75]
FrontEnd implementation for weather API needs to be implemented.

**Comment by alcanunsal** [comment]
Frontend implementation in index.html about Weather API is mostly done. We only need to focus one make-up: images, orientation, buttons etc.

**Comment by alcanunsal** [comment]
@hasandemirkiran I believe we can close this issue now that the implementation is done for the frontend. What do you say?

**Comment by hasandemirkiran** [comment]
I have checked clearly and didn't see anything to prevent closing the issue. Some minimal changes can made after closing the issue.
