### ISSUE TITLE
Create first issues

### ISSUE THREAD

**Issue by firatbulut19** [bounswe/bounswe2020group9#9]
Create the first issues.

**Comment by mericturan** [comment]
Can anyone tell me the objective of this issue?

**Comment by firatbulut19** [comment]
Creating issues was one of the tasks we discussed in the first group meeting. I was assigned to the task and created the issues according to the meeting notes. 
I added this issue as well, since "Creating first issues" was one of the tasks and I thought it was supposed to be documented in the issues page. 
It seems redundant now, though.

**Comment by mericturan** [comment]
We wanted you to document, but not in such a way. Nevertheless, from now on, please try to write full (i.e., subject, object, and verb) and more descriptive sentences in the description part of the issues.
