### ISSUE TITLE
frameworks to use

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#98]
here we could discuss the frameworks to use.

**Comment by alcanunsal** [comment]
Backend: MYsql, Django, DjangoRestFramework
Frontend: Django, Bootstrap
IOS: Swift, XCode

Are these OK to use? Is there anything that can be added?

**Comment by muhsinetki** [comment]
I think it is suitable for mobile to use iOS.

**Comment by firatbulut19** [comment]
We can additionally use React for Frontend.

**Comment by hasandemirkiran** [comment]
We may choose which design libraries we are going to use. AntD, Boootstrap4, MD...

**Comment by ocebenzer** [comment]
on top of frameworks, we might need additional packages such as django-allauth in order to login via google
it'd be good to write them all down

**Comment by ocebenzer** [comment]
IOS Development got approved!

**Comment by alcanunsal** [comment]
If we decided on all the frameworks, I think we can close this issue now.

**Comment by hasandemirkiran** [comment]
We can close the issue now.
