### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#99]
Update requirements according to the customer feedbacks

**Comment by sadiuysal** [comment]
Please examine class diagram according to requirements and report your feedbacks until the [next meeting](https://github.com/bounswe/bounswe2020group9/issues/108).

**Comment by m-canunal** [comment]
It looks generally fine i made few changes, 
-forgotten password option
-stock status.
In class diagram we can add filterByStockstatus into FilterEngine to remove out of stock products.

**Comment by alcanunsal** [comment]
Since the reviews has been done, I propose that we can close this issue now.
